CREATE TABLE SERVICO (
  ID SERIAL,
  CODIGO INTEGER,
  DESCRICAO VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
  ID SERIAL,
  LOGIN VARCHAR(20) NOT NULL,
  SENHA VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE GRUPO (
  ID SERIAL,
  CODIGO INTEGER,
  NOME VARCHAR(45) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE A_USUARIO_GRUPO (
  USUARIO_ID INTEGER NOT NULL,
  GRUPO_ID INTEGER NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NULL,
  PRIMARY KEY(USUARIO_ID, GRUPO_ID),
  FOREIGN KEY(USUARIO_ID)
    REFERENCES USUARIO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(GRUPO_ID)
    REFERENCES GRUPO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE A_GRUPO_SERVICO (
  GRUPO_ID INTEGER NOT NULL,
  SERVICO_ID INTEGER NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NULL,
  PRIMARY KEY(GRUPO_ID, SERVICO_ID),  
  FOREIGN KEY(GRUPO_ID)
    REFERENCES GRUPO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SERVICO_ID)
    REFERENCES SERVICO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


